### ISSUE TITLE
[BUG] node:child_process:826     err = new Error(msg)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [izu-co/funimation-downloader-nx#11]
** Main info: **

Script version: 4.8.1
Show ID: 1315001
Episode ID: 11

** Additional Info: **
```
[INFO] Finished /Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts

> "mkvmerge" @"/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].json"
mkvmerge v58.0.0 ('Supper's Ready') 64-bit
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
Warning: '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts': A track with the ID 1 was requested but not found in the file. The corresponding option will be ignored.
The file '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].mkv' has been opened for writing.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 7 seconds.
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: "/usr/local/bin/mkvmerge" @"/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].json"
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exec (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/node_modules/sei-helper/src/main.js:174:30)
    at downloadStreams (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/funi.js:712:14)
    at async getEpisode (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/funi.js:383:13)
    at async getShow (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/funi.js:259:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13001,
  stdout: null,
  stderr: null
}
```

it muxes but fails to delete the .ts & json file.
this started happening after I did an npm update command as I usually do every week
even doing a fresh install of the modules will get the latest ver soo...

**Comment by izu-co** [comment]
The error comes from the kind of ugly way anidl implemented the muxing.

While working on #10 I redid it and studied the docs on FFmpeg and mkvmerge. Please note that the fix for this will most likely have to wait until the PR is merged. 

Sorry about that one, but the PR is taking all my time.

It will remain open until the PR is merged, and you can confirm that the error vanished.

**Comment by XxUnkn0wnxX** [comment]
@izu-co will you merge into yours? as I'm mainly using yours as you keep it up to date with new goodies
I'm on master branch...

**Comment by izu-co** [comment]
Yes. Since Anidl is inactive, I kind of dedicated myself to maintaining this project.
I won't create PR into Anidl's repo any time soon.

**Comment by XxUnkn0wnxX** [comment]
I switch to `multiple-audio-and-subtitles`
as a test, still getting

```
> "mkvmerge" -o "/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --track-name 0:[Funimation] --language 1:eng --video-tracks 0 --audio-tracks 1 "/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts" --no-subtitles --no-attachments
mkvmerge v58.0.0 ('Supper's Ready') 64-bit
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts': Using the demultiplexer for the format 'MPEG transport stream'.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
Warning: '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts': A track with the ID 1 was requested but not found in the file. The corresponding option will be ignored.
The file '/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].mkv' has been opened for writing.
'/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 1920/1080.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 7 seconds.
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: "/usr/local/bin/mkvmerge" -o "/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].mkv" --no-date --disable-track-statistics-tags --engage no_variable_data --track-name 0:[Funimation] --language 1:eng --video-tracks 0 --audio-tracks 1 "/Users/ADMIN/Downloads/AppDL/funi/[Funimation] Bottom-Tier Character Tomozaki - 11 [1080p].ts" --no-subtitles --no-attachments
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.exec (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/node_modules/sei-helper/src/main.js:174:30)
    at downloadStreams (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/funi.js:695:14)
    at async getEpisode (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/funi.js:399:13)
    at async getShow (/Users/ADMIN/Apps/Animie/izu-co/funimation-downloader-nx/funi.js:272:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26441,
  stdout: null,
  stderr: null
}
```

also no Audio in the mkv file...

**Comment by izu-co** [comment]
The PR is by no means ready. I try to get a kind of working version of beta testing today.

**Comment by izu-co** [comment]
Please download the new [release](https://github.com/izu-co/funimation-downloader-nx/releases/tag/4.9.0) and test it. 

If you find any errors, open a new issue, please.
