### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by OryWareKyrie** [izu-co/funimation-downloader-nx#17]
** Main info: **

Script version: 4.9.1
Show ID: 19373
Episode ID: 9

** Additional Info: **
Does anyone know why this error? the binary version for windows is working. but when I try the code version this error appears.

```
[INFO] Selected layer: 7 (1280x720) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/1441106/English/1441106_English_7479951_d9735345-9c1b-e611-80c5-0017a4776c06_Layer7.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xNDQxMTA2L0VuZ2xpc2gvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyNTk2MDI5NH19fV19&Signature=L1y~R424B1bZIAEVte4diA6FDHg-CAoOEqnjPLdAWwEswJSzpfeg1SjDkSuHCQxVxIEJiBoupqKh1tXNjL~0Wwa0aVzki7dq8OZz30zI8vf0GeoCJJ~Xjt-KuRhyplJ2RD08gruZ6YSieZt7Obm0a0NBRnoybEdqzH4LJzdrKyfkc~JhgJuv9c4IIw9Vl5drj08zTozc7lRsLzvIWCsjJAWvRodTDXtdo-unHLQf64v3XFR-t7IhMb7XBYKLw3zqlvA4SdwOsbHLTx2la1JzsGyMpyACgIJh-bjlta5oRhvJxV5P2vcrxbfhgQUld0jFKb~ELtv3Wt-ou7n3wTTbcw__&rt=1387046
[INFO] Output filename: [Funimation] Assassination Classroom - 09 [720p].ts
[INFO] Started C:\Users\crazy\Downloads\Compressed\funimation-downloader-nx-4.9.1\videos\[Funimation] Assassination Classroom - 09 [720p].video.en.ts
(node:10584) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\crazy\Downloads\Compressed\funimation-downloader-nx-4.9.1\videos\[Funimation] Assassination Classroom - 09 [720p].video.en.ts.resume'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at downloadFile (C:\Users\crazy\Downloads\Compressed\funimation-downloader-nx-4.9.1\funi.js:776:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadStreams (C:\Users\crazy\Downloads\Compressed\funimation-downloader-nx-4.9.1\funi.js:618:25)
    at async getEpisode (C:\Users\crazy\Downloads\Compressed\funimation-downloader-nx-4.9.1\funi.js:415:13)
    at async getShow (C:\Users\crazy\Downloads\Compressed\funimation-downloader-nx-4.9.1\funi.js:272:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Astyre** [comment]
It looks like you just need to create a "videos" folder inside your funimation downloader folder.

**Comment by OryWareKyrie** [comment]
@Astyre Our came to my face and I saw... 😄  thank you very much friend
